# Generated by Django 4.2.24 on 2025-09-18 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pelicula',
            options={},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='disponible',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='duracion_minutos',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='fecha_estreno',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='notas',
        ),
    ]
