# Generated by Django 4.2.24 on 2025-09-18 18:34

from django.db import migrations


def populate_initial_movies(apps, schema_editor):
    """
    Populate initial movie data following DRY principle
    """
    Pelicula = apps.get_model('core', 'Pelicula')
    
    # Lista de películas iniciales
    movies = ['Matrix', 'Inception', 'Interstellar']
    
    for movie_title in movies:
        # Evitar duplicados usando get_or_create (DRY)
        Pelicula.objects.get_or_create(titulo=movie_title)


def reverse_populate_movies(apps, schema_editor):
    """
    Rollback function to remove initial movies
    """
    Pelicula = apps.get_model('core', 'Pelicula')
    
    initial_movies = ['Matrix', 'Inception', 'Interstellar']
    Pelicula.objects.filter(titulo__in=initial_movies).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_pelicula_options_alter_reserva_options_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_initial_movies, reverse_populate_movies),
    ]
