# Generated by Django 4.2.24 on 2025-09-18 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20250918_1334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pelicula',
            options={'verbose_name': 'Película', 'verbose_name_plural': 'Películas'},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='reserva',
            name='cantidad_boletos',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='pelicula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.pelicula'),
        ),
        migrations.AlterModelTable(
            name='pelicula',
            table='peliculas',
        ),
        migrations.AlterModelTable(
            name='reserva',
            table='reservas',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('fecha', models.DateField()),
                ('sala', models.CharField(default='Sala 1', max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, default=10.0, max_digits=8)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pelicula')),
            ],
            options={
                'verbose_name': 'Función',
                'verbose_name_plural': 'Funciones',
                'db_table': 'funciones',
                'unique_together': {('pelicula', 'fecha', 'hora_inicio', 'sala')},
            },
        ),
        migrations.AddField(
            model_name='reserva',
            name='funcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.funcion'),
        ),
    ]
