# Generated by Django 4.2.24 on 2025-09-18 19:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_pelicula_options_alter_reserva_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='funcion',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='cantidad_boletos',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='pelicula',
        ),
        migrations.AddField(
            model_name='funcion',
            name='fecha_hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='duracion_minutos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='genero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='sinopsis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='cantidad_asientos',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='funcion',
            name='pelicula',
            field=models.ForeignKey(db_column='pelicula_id', on_delete=django.db.models.deletion.CASCADE, to='core.pelicula'),
        ),
        migrations.AlterField(
            model_name='funcion',
            name='sala',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='funcion',
            field=models.ForeignKey(db_column='funcion_id', default=1, on_delete=django.db.models.deletion.RESTRICT, to='core.funcion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuarios',
        ),
        migrations.RemoveField(
            model_name='funcion',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='funcion',
            name='hora_inicio',
        ),
        migrations.RemoveField(
            model_name='funcion',
            name='precio',
        ),
    ]
